import React from 'react';
import { useAuctionStore } from '../../store/auctionStore';

export function StepExplanation() {
  const { currentStep, bids, itemCount, results } = useAuctionStore();

  const getStepContent = () => {
    switch (currentStep) {
      case 0:
        return {
          title: 'Step 1: Sort Bids',
          content: [
            'All bids are sorted in descending order.',
            `The top ${itemCount} bids will be winning bids.`,
            'Winning bids are highlighted in green.'
          ],
          formula: '𝐵 = {𝑏₁, 𝑏₂, ..., 𝑏ₙ} where 𝑏₁ ≥ 𝑏₂ ≥ ... ≥ 𝑏ₙ',
          explanation: 'This step identifies the most valuable bids that will win the auction.'
        };
      case 1:
        return {
          title: 'Step 2: Calculate Total Value (V*)',
          content: [
            'Sum all winning bids to get V*.',
            `Current V* = $${results?.totalValue || 0}`,
            'This represents the maximum value achievable from the auction.'
          ],
          formula: 'V* = ∑ᵢ₌₁ᵏ 𝑏ᵢ where k = number of items',
          explanation: 'Total value shows the maximum economic value generated by the auction before applying Vickrey pricing.'
        };
      case 2:
        return {
          title: 'Step 3: Calculate V*j',
          content: [
            'For each winner, calculate the auction value without their bids.',
            'This shows the impact of each bidder on the total auction value.',
            'Recalculate total value with replacement bids.'
          ],
          formula: 'V*ⱼ = ∑ᵢ₌₁ᵏ 𝑏ᵢ where 𝑏ᵢ ∉ Bⱼ',
          explanation: 'V*j represents the total value of the auction if a specific bidder were removed. This helps determine the true economic impact of each bidder.'
        };
      case 3:
        return {
          title: 'Step 4: Compute Vickrey Prices',
          content: [
            'Calculate the price each winner must pay.',
            'Price is based on the economic impact of their bids.',
            'Ensures bidders pay the opportunity cost they create.'
          ],
          formula: 'Pⱼ = V*ⱼ - (V* - ∑ᵢ∈Wⱼ 𝑏ᵢ)\nwhere Wⱼ = winning bids of bidder j',
          explanation: 'Vickrey pricing ensures that winners pay a fair price based on how their participation affects other bidders. It discourages strategic bidding.'
        };
      default:
        return {
          title: 'Complete',
          content: ['All steps completed. Review the results or start over.'],
          explanation: 'You have now seen the complete Vickrey auction mechanism.'
        };
    }
  };

  const stepContent = getStepContent();

  return (
    <div className="bg-gray-50 p-4 rounded-lg">
      <h3 className="text-lg font-semibold mb-4">{stepContent.title}</h3>
      <div className="space-y-4">
        {stepContent.content.map((text, index) => (
          <p key={index} className="text-sm text-gray-700">{text}</p>
        ))}
      </div>
      {stepContent.formula && (
        <div className="mt-4 p-3 bg-white rounded border border-gray-200">
          <p className="text-sm font-medium text-gray-600">Formula:</p>
          <div className="mt-1 font-mono text-sm bg-gray-50 p-3 rounded whitespace-pre-wrap text-center">
            {stepContent.formula}
          </div>
        </div>
      )}
      {stepContent.explanation && (
        <div className="mt-4 p-3 bg-blue-50 rounded">
          <p className="text-sm text-blue-800">{stepContent.explanation}</p>
        </div>
      )}
    </div>
  );
}